### ISSUE TITLE
Could not find ro.holdone.keyboardHeightProvider:1.0.1

### ISSUE THREAD

**Issue by mrvinay07** [Crysis21/KeyboardHeightProvider#16]
This issue came to only in Android Studio Arctic Fox | 2020.3.1 Latest version
I replace this dependency with the latest one but the problem is the same.

> Could not find ro.holdone.keyboardHeightProvider:1.0.1:.
     Required by:
         project :app

I can't understand what to do to resolve this issue.

**Comment by Crysis21** [comment]
I will check it. It's strange.

**Comment by Crysis21** [comment]
library is on maven. Can you please check if you have `mavenCentral` in your repos list?

Also, I published an update today.

https://search.maven.org/artifact/ro.holdone/keyboardheightprovider/1.0.2/aar

**Comment by mrvinay07** [comment]
I checked I have mavenCentral() in my repositories list. I also updated the dependency with the latest version 1.0.2 but the problem is not resolved. Even your GitHub project is not running on the latest android studio I clone your project from github and got the same error.

https://github.com/Crysis21/KeyboardHeightProvider

repositories list-
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()

    }

**Comment by Crysis21** [comment]
fixed in 1.0.3. there was a mistake in generated gradle POM

**Comment by mrvinay07** [comment]
Hello  Bro... Still, it shows the same error after updating the latest library 1.0.3.

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
###   > Could not find ro.holdone.keyboardHeightProvider:1.0.3:.
     Required by:
         project :app
